// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onfvykbgnysenkszhrpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uZnZ5a2JnbnlzZW5rc3pocnBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMzcwMzMsImV4cCI6MjA3MDgxMzAzM30.sidF2lUnWua3usX5Aeth4sSn5NGomWWciqZn1gBOAfU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});